# Function to add intervention labels and to add age group label

add_labels <- function(df){
  out <- df %>%
    mutate(strategytype = ifelse(PEVstrategy == "AB" | PEVstrategy == 'hybrid' | PEVstrategy == 'SV', 'Routine',
                                 ifelse(PEVstrategy == 'catch-up', 'Catch-up',
                                        ifelse(PEVstrategy == 'mass', 'Mass',
                                               ifelse(PEVstrategy == 'none','No vaccine', NA))))) %>%
    mutate(label_int = paste(PEVstrategy, PEVage, PEVrounds, EPIbooster, EPIextra, massbooster_rep),
           labels = case_when(label_int == "AB - - 12m - -"  ~ 'Routine age-based',
                              label_int == "AB - - 12m boost - -"  ~ '12m booster with higher titre',
                              label_int == "AB - - 18m - -" ~ '18m booster',
                              label_int == "AB - - 12m 10y -" ~ "10y booster",
                              label_int == 'AB - - 12m 5y -' ~ "5y booster",
                              label_int == 'AB - - 12m 2y -' ~ "2y booster",
                              label_int == 'AB - - 12m 5y+10y -' ~ "5y, 10y boosters",
                              label_int == 'AB - - 12m 2y+10y -' ~ "2y, 10y boosters",
                              label_int == 'AB - - 12m 2y+5y -' ~ "2y, 5y boosters",
                              label_int == 'AB - - 12m 2y+5y+10y -' ~ "2y, 5y, 10y boosters",
                              label_int == 'SV - - seasonal - -' ~ 'Seasonal vaccination',
                              label_int == 'hybrid - - seasonal - -' ~ 'Hybrid vaccination',
                              label_int == 'catch-up 5-14 - 12m boost - -' | label_int == 'catch-up 5-14 - 12m - -' ~ '5-14y',
                              label_int == 'catch-up 5-14 - 12m boost 10y -' | label_int == 'catch-up 5-14 - 12m 10y -' ~ '5-14y;\n10y booster',
                              label_int == 'catch-up 5-14 - 12m boost 5y -' | label_int == 'catch-up 5-14 - 12m 5y -' ~ '5-14y;\n5y booster',
                              label_int == 'catch-up 5-14 - 12m boost 2y -' | label_int == 'catch-up 5-14 - 12m 2y -' ~ '5-14y;\n2y booster',
                              label_int == 'catch-up 5-14 - 12m boost 5y+10y -' | label_int == 'catch-up 5-14 - 12m 5y+10y -' ~ '5-14y;\n5y, 10y boosters',
                              label_int == 'catch-up 5-14 - 12m boost 2y+10y -' | label_int == 'catch-up 5-14 - 12m 2y+10y -' ~ '5-14y;\n2y, 10y boosters',
                              label_int == 'catch-up 5-14 - 12m boost 2y+5y -' | label_int == 'catch-up 5-14 - 12m 2y+5y -' ~ '5-14y;\n2y, 5y boosters',
                              label_int == 'catch-up 5-14 - 12m boost 2y+5y+10y -' | label_int == 'catch-up 5-14 - 12m 2y+5y+10y -' ~ '5-14y;\n2y, 5y, 10y boosters',
                              label_int == 'catch-up 5-9 - 12m boost - -' | label_int == 'catch-up 5-9 - 12m - -' ~ '5-9y',
                              label_int == 'catch-up 5-9 - 12m boost 10y -' | label_int == 'catch-up 5-9 - 12m 10y -' ~ '5-9y;\n10y booster',
                              label_int == 'catch-up 5-9 - 12m boost 5y -' | label_int == 'catch-up 5-9 - 12m 5y -' ~ '5-9y;\n5y booster',
                              label_int == 'catch-up 5-9 - 12m boost 2y -' | label_int == 'catch-up 5-9 - 12m 2y -' ~ '5-9y;\n2y booster',
                              label_int == 'catch-up 5-9 - 12m boost 5y+10y -' | label_int == 'catch-up 5-9 - 12m 5y+10y -' ~ '5-9y;\n5y, 10y boosters',
                              label_int == 'catch-up 5-9 - 12m boost 2y+10y -' | label_int == 'catch-up 5-9 - 12m 2y+10y -' ~ '5-9y;\n2y, 10y boosters',
                              label_int == 'catch-up 5-9 - 12m boost 2y+5y -' | label_int == 'catch-up 5-9 - 12m 2y+5y -' ~ '5-9y;\n2y, 5y boosters',
                              label_int == 'catch-up 5-9 - 12m boost 2y+5y+10y -' | label_int == 'catch-up 5-9 - 12m 2y+5y+10y -' ~ '5-9y;\n2y, 5y, 10y boosters',
                              label_int == 'catch-up 6m-14y - 12m - -' ~ '6m-14y',
                              label_int == 'catch-up 6m-14y - 12m 10y -' ~ '6m-14y;\n10y booster',
                              label_int == 'catch-up 6m-14y - 12m 2y -' ~ '6m-14y;\n2y booster',
                              label_int == 'catch-up 6m-14y - 12m 5y -' ~ '6m-14y;\n5y booster',
                              label_int == 'catch-up 6m-14y - 12m 5y+10y -' ~ '6m-14y;\n5y, 10y boosters',
                              label_int == 'catch-up 6m-14y - 12m 2y+5y -' ~ '6m-14y;\n2y, 5y boosters',
                              label_int == 'catch-up 6m-14y - 12m 2y+10y -' ~ '6m-14y;\n2y, 10y boosters',
                              label_int == 'catch-up 6m-14y - 12m 2y+5y+10y -' ~ '6m-14y;\n2y, 5y, 10y boosters',
                              label_int == 'catch-up 6m-2y - 12m - -' ~ '6m-2y',
                              label_int == 'catch-up 6m-2y - 12m 10y -' ~ '6m-2y;\n10y booster',
                              label_int == 'catch-up 6m-2y - 12m 5y -' ~ '6m-2y;\n5y booster',
                              label_int == 'catch-up 6m-2y - 12m 2y -' ~ '6m-2y;\n2y booster',
                              label_int == 'catch-up 6m-2y - 12m 5y+10y -' ~ '6m-2y;\n5y, 10y boosters',
                              label_int == 'catch-up 6m-2y - 12m 2y+5y -' ~ '6m-2y;\n2y, 5y boosters',
                              label_int == 'catch-up 6m-2y - 12m 2y+10y -' ~ '6m-2y;\n2y, 10y boosters',
                              label_int == 'catch-up 6m-2y - 12m 2y+5y+10y -' ~ '6m-2y;\n2y, 5y, 10y boosters',
                              label_int == 'catch-up 6m-4y - 12m - -' ~ '6m-4y',
                              label_int == 'catch-up 6m-4y - 12m 10y -' ~ '6m-4y;\n10y booster',
                              label_int == 'catch-up 6m-4y - 12m 5y -' ~ '6m-4y;\n5y booster',
                              label_int == 'catch-up 6m-4y - 12m 2y -' ~ '6m-4y;\n2y booster',
                              label_int == 'catch-up 6m-4y - 12m 5y+10y -' ~ '6m-4y;\n5y, 10y boosters',
                              label_int == 'catch-up 6m-4y - 12m 2y+5y -' ~ '6m-4y;\n2y, 5y boosters',
                              label_int == 'catch-up 6m-4y - 12m 2y+10y -' ~ '6m-4y;\n2y, 10y boosters',
                              label_int == 'catch-up 6m-4y - 12m 2y+5y+10y -' ~ '6m-4y;\n2y, 5y, 10y boosters',
                              label_int == 'catch-up 6m-9y - 12m - -' ~ '6m-9y',
                              label_int == 'catch-up 6m-9y - 12m 10y -' ~ '6m-9y;\n10y booster',
                              label_int == 'catch-up 6m-9y - 12m 5y -' ~ '6m-9y;\n5y booster',
                              label_int == 'catch-up 6m-9y - 12m 2y -' ~ '6m-9y;\n2y booster',
                              label_int == 'catch-up 6m-9y - 12m 5y+10y -' ~ '6m-9y;\n5y, 10y boosters',
                              label_int == 'catch-up 6m-9y - 12m 2y+5y -' ~ '6m-9y;\n2y, 5y boosters',
                              label_int == 'catch-up 6m-9y - 12m 2y+10y -' ~ '6m-9y;\n2y, 10y boosters',
                              label_int == 'catch-up 6m-9y - 12m 2y+5y+10y -' ~ '6m-9y;\n2y, 5y, 10y boosters',
                              label_int == 'none - - - - -' ~ 'None'),
           labels = factor(labels, levels = c('Routine age-based', "2y booster","5y booster", "10y booster","5y, 10y boosters",
                                              '2y, 5y boosters','2y, 10y boosters', '2y, 5y, 10y boosters',
                                              'Seasonal vaccination', 'Hybrid vaccination',
                                              '6m-2y', '6m-2y;\n2y booster', '6m-2y;\n5y booster', '6m-2y;\n10y booster', '6m-2y;\n5y, 10y boosters','6m-2y;\n2y, 5y boosters','6m-2y;\n2y, 10y boosters','6m-2y;\n2y, 5y, 10y boosters',
                                              '6m-4y', '6m-4y;\n2y booster', '6m-4y;\n5y booster', '6m-4y;\n10y booster', '6m-4y;\n5y, 10y boosters','6m-4y;\n2y, 5y boosters','6m-4y;\n2y, 10y boosters','6m-4y;\n2y, 5y, 10y boosters',
                                              '6m-9y', '6m-9y;\n2y booster', '6m-9y;\n5y booster', '6m-9y;\n10y booster', '6m-9y;\n5y, 10y boosters','6m-9y;\n2y, 5y boosters','6m-9y;\n2y, 10y boosters','6m-9y;\n2y, 5y, 10y boosters',
                                              '6m-14y', '6m-14y;\n2y booster', '6m-14y;\n5y booster', '6m-14y;\n10y booster', '6m-14y;\n5y, 10y boosters','6m-14y;\n2y, 5y boosters','6m-14y;\n2y, 10y boosters','6m-14y;\n2y, 5y, 10y boosters',
                                              '5-9y', '5-9y;\n2y booster', '5-9y;\n5y booster', '5-9y;\n10y booster', '5-9y;\n5y, 10y boosters','5-9y;\n2y, 5y boosters','5-9y;\n2y, 10y boosters','5-9y;\n2y, 5y, 10y boosters',
                                              '5-14y', '5-14y;\n2y booster', '5-14y;\n5y booster', '5-14y;\n10y booster', '5-14y;\n5y, 10y boosters','5-14y;\n2y, 5y boosters','5-14y;\n2y, 10y boosters','5-14y;\n2y, 5y, 10y boosters',
                                              'None')),
           EPIextra_labels = case_when(EPIextra == '-'~ '12m only', 
                                       EPIextra == '5y' ~ '12m + 5y',
                                       EPIextra == '2y' ~ '12m + 2y',
                                       EPIextra == '10y'~ '12m + 10y',
                                       EPIextra == '5y+10y' ~ "12m + 5y + 10y",
                                       EPIextra == '2y+5y' ~ '12m + 2y + 5y',
                                       EPIextra == '2y+10y' ~ '12m + 2y + 10y',
                                       EPIextra == '2y+5y+10y' ~ '12m + 2y + 5y + 10y'),
           EPIextra_labels = factor(EPIextra_labels, levels = c('12m only', '12m + 2y', '12m + 5y', '12m + 10y', '12m + 5y + 10y','12m + 2y + 5y','12m + 2y + 10y','12m + 2y + 5y + 10y')),
           scen_labels = case_when(EPIextra == '-' & PEVstrategy == 'catch-up' ~ 'Catch-up with \n12m AB booster',
                                   EPIextra == '-' & PEVstrategy == 'AB' ~ 'Routine only',
                                   EPIextra == '5y' & PEVstrategy == 'catch-up'~ 'Catch-up with \n12m, 5y AB boosters',
                                   EPIextra == '2y' & PEVstrategy == 'catch-up'~ 'Catch-up with \n12m, 2y AB boosters',
                                   EPIextra == '10y'& PEVstrategy == 'catch-up' ~ 'Catch-up with \n12m, 10y AB boosters',
                                   EPIextra == '5y+10y' & PEVstrategy == 'catch-up'~ 'Catch-up with \n12m, 5y, 10y AB boosters',
                                   EPIextra == '2y+10y' & PEVstrategy == 'catch-up'~ 'Catch-up with \n12m, 2y, 10y AB boosters',
                                   EPIextra == '2y+5y' & PEVstrategy == 'catch-up'~ 'Catch-up with \n12m, 2y, 5y AB boosters',
                                   EPIextra == '2y+5y+10y' & PEVstrategy == 'catch-up'~ 'Catch-up with \n12m, 2y, 5y, 10y AB boosters'),
           scen_labels = factor(scen_labels, levels = c('Routine only','Catch-up with \n12m AB booster','Catch-up with \n12m, 2y AB boosters', 'Catch-up with \n12m, 5y AB boosters',
                                                        'Catch-up with \n12m, 10y AB boosters','Catch-up with \n12m, 2y, 10y AB boosters','Catch-up with \n12m, 2y, 5y AB boosters',
                                                        'Catch-up with \n12m, 2y, 5y, 10y AB boosters')))
  
  return(out)
}
